function[zs]=dve_angledata(pol,azi,theta,phi,phi0,theta0,zs,V0,j,k,d1,d2,d3)
% Purpose: Formats and prints angle data to the figure for easy reading.
   
% nxorig=zs(1);
% nyorig=zs(2);
% nzorig=zs(3);
% theta0=acosd(zs(1));
% phi0=atand(zs(2)/zs(1));
% %-------------------------------------%
% % set phi0 based on nxorig and nyorig %
% %-------------------------------------%
% if (nxorig < 0.0) && (nyorig >= 0.0);
%   phi0=-phi0+180.;
% end
% if (nxorig < 0.0) && (nyorig < 0.0);
%   phi0= phi0+180.;
% end
% if (nxorig >= 0.0) && (nyorig < 0.0);
%   phi0=-phi0+360.;
% end

    %---------------------------------------%
    % Display Relevant Values on GUI Window %
    %---------------------------------------%    
    pan1 = uipanel('Position', [.01 .33 .98 .30],...
      'BorderWidth',3,...
      'FontSize',12,...
      'ForegroundColor','k',...
      'ShadowColor','k',...
      'BorderType','etchedout',...
      'TitlePosition','lefttop',...
      'FontWeight', 'light');
    %-1st Column Subpanels--------------------------------------------------
    % Polar subpanel %
    subpan1a = uipanel(pan1,'Position', [.01 .50 .20 .48],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','Azimuth',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');    
    % Azimuth subpanel %
    subpan1b = uipanel(pan1,'Position', [.01 .01 .20 .48],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','Polar',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');
    % Azimuth Text %
    txt1=uicontrol(subpan1a,'Style','text',...
       'String',[num2str(azi, '%0.3g'),char(176)],...
       'Position', [4 01 80 40],...
       'FontSize',28,...
       'FontName','Helvetica',...
       'ForegroundColor', 'green',...
       'HorizontalAlignment','Center');
    % Polar Text %
    txt2=uicontrol(subpan1b,'Style','text',...
       'String',[num2str(pol,'%0.3g'),char(176)],...
       'FontSize',28,...
       'FontName','Helvetica',...
       'Position', [4 01 80 40],...
       'ForegroundColor', 'blue',...
       'HorizontalAlignment','Center');
    %---2nd Column Top Subpanel-------------------------------------------------
    % Phi Panel + Title %
    subpan1a = uipanel(pan1,'Position', [.22 .50 .20 .48],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','Phi (GSM)',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');    
    % Theta Panel + Title %
    subpan1b = uipanel(pan1,'Position', [.22 .01 .20 .48],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','Theta (GSM)',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');
    % Phi Text
    txt3=uicontrol(subpan1a,'Style','text',...
       'String',[num2str(phi, '%0.3g'),char(176)],...
       'FontSize',32,...
       'FontName','Helvetica',...
       'Position', [4 01 100 40],...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Center');
    % Theta Text %
    txt4=uicontrol(subpan1b,'Style','text',...
       'String',[num2str(theta,'%0.3g'),char(176)],...
       'Position', [4 01 100 40],...
       'FontSize',28,...
       'FontName','Helvetica',...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Center');
    %--------3rd Column Top Subpanel------------------------------------------
     % J subpanel
    subpan1c = uipanel(pan1,'Position', [.44 .50 .20 .48],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','Phi #',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');    
    % K subpanel %
    subpan1d = uipanel(pan1,'Position', [.44 .01 .20 .48],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','Theta #',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');  
    % J Text %
    txt11=uicontrol(subpan1c,'Style','text',...
       'String',num2str(k,'%0.3g'),...
       'FontSize',28,...
       'FontName','Helvetica',...
       'Position', [4 01 80 40],...
       'ForegroundColor', 'blue',...
       'HorizontalAlignment','Center');
    % K Text %
    txt12=uicontrol(subpan1d,'Style','text',...
       'String',num2str(j,'%0.3g'),...
       'Position', [4 01 80 40],...
       'FontSize',28,...
       'FontName','Helvetica',...
       'ForegroundColor', 'green',...
       'HorizontalAlignment','Center');    
    %----4th Column Top Subpanel-----------------------------------------------
    % Phi0 subpanel %
    subpan1e = uipanel(pan1,'Position', [.66 .50 .20 .48],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','Phi0 (GSM)',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');    
    % Theta0 subpanel %
    subpan1f = uipanel(pan1,'Position', [.66 .01 .20 .48],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','Theta0 (GSM)',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');
    % Phi0 Text %
    txt1=uicontrol(subpan1e,'Style','text',...
       'String',[num2str(phi0,'%0.3g'),char(176)],...
       'FontSize',28,...
       'FontName','Helvetica',...
       'Position', [4 01 80 40],...
       'ForegroundColor', 'blue',...
       'HorizontalAlignment','Center');
    % Theta0 Text %
    txt2=uicontrol(subpan1f,'Style','text',...
       'String',[num2str(theta0, '%3.1g'),char(176)],...
       'Position', [4 01 80 40],...
       'FontSize',28,...
       'FontName','Helvetica',...
       'ForegroundColor', 'green',...
       'HorizontalAlignment','Center');
     
%============================BOTTOM BIG PANEL=====================================%

    pan2 = uipanel('Position', [.01 .01 .98 .30],...
      'BorderWidth',3,...
      'FontSize',12,...
      'ForegroundColor','k',...
      'ShadowColor','k',...
      'BorderType','etchedout',...
      'TitlePosition','lefttop',...
      'FontWeight', 'light');
    %------------------1st column bottom subpanel---------------------------
    subpan2a = uipanel(pan2,'Position', [.01 .01 .20 .98],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','V0 (km/s in GSM)',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');
    % V0 (xGSM) Text
    txt5=uicontrol(subpan2a,'Style','text',...
       'String',['x= ',num2str(V0(1), '%1.3g')],...
       'FontSize',20,...
       'FontName','Helvetica',...
       'Position', [4 60 100 40],...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Left');
    % V0 (yGSM) Text %
    txt6=uicontrol(subpan2a,'Style','text',...
       'String',['y= ',num2str(V0(2),'%1.3g')],...
       'Position', [4 30 100 40],...
       'FontSize',20,...
       'FontName','Helvetica',...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Left');
    % V0 (zGSM) Text
    txt7=uicontrol(subpan2a,'Style','text',...
       'String',['z= ',num2str(V0(3), '%1.3g')],...
       'FontSize',20,...
       'FontName','Helvetica',...
       'Position', [4 01 100 40],...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Left');
    %------------------2nd column bottom subpanel---------------------------
    subpan2b = uipanel(pan2,'Position', [.22 .01 .20 .98],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','ZS (unit)',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');
    % zs (xGSM) Text
    txt8=uicontrol(subpan2b,'Style','text',...
       'String',['x= ',num2str(zs(1), '%0.3g')],...
       'FontSize',20,...
       'FontName','Helvetica',...
       'Position', [4 60 100 40],...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Left');
    % zs (yGSM) Text %
    txt9=uicontrol(subpan2b,'Style','text',...
       'String',['y= ',num2str(zs(2),'%0.3g')],...
       'Position', [4 30 100 40],...
       'FontSize',20,...
       'FontName','Helvetica',...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Left');
    % zs (zGSM) Text
    txt10=uicontrol(subpan2b,'Style','text',...
       'String',['z= ',num2str(zs(3), '%0.3g')],...
       'FontSize',20,...
       'FontName','Helvetica',...
       'Position', [4 01 100 40],...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Left');
     %----------3rd Column Bottom Subpanel----------------------------
     % Eigenvalues Subpanel
    subpan2c = uipanel(pan2,'Position', [.44 .01 .20 .98],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title', 'Eigenvalues',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');    
    % EigenCheck Subpanel
    subpan2d = uipanel(pan2,'Position', [.66 .01 .20 .98],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','Greater than 10?',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');  
      % eigenvalue 1 text %
    txt11=uicontrol(subpan2c,'Style','text',...
       'String',['d1= ', num2str(d1, '%0.3g')],...
       'FontSize',14,...;
       'FontName','Helvetica',...;
       'Position', [4 56 80 40],...;
       'ForegroundColor', 'blue',...;
       'HorizontalAlignment','Left');
           % eigenvalue 2 text %
    txt11=uicontrol(subpan2c,'Style','text',...
       'String',['d2= ', num2str(d2, '%1.3g')],...
       'FontSize',14,...;
       'FontName','Helvetica',...;
       'Position', [4 28 80 40],...;
       'ForegroundColor', 'blue',...;
       'HorizontalAlignment','Left');
           % eigenvalue 3 text %
    txt11=uicontrol(subpan2c,'Style','text',...
       'String',['d3= ', num2str(d3, '%3.1g')],...
       'FontSize',14,...;
       'FontName','Helvetica',...;
       'Position', [4 01 80 40],...;
       'ForegroundColor', 'blue',...;
       'HorizontalAlignment','Left');
    % eigenvalue quality check d2 %
    txt12=uicontrol(subpan2d,'Style','text',...
       'String','d2',...
       'Position', [4 40 80 40],...
       'FontSize',18,...
       'FontName','Helvetica',...
       'ForegroundColor', 'green',...
       'HorizontalAlignment','Left');
    % eigenvalue quality check '__=' %
    txt12=uicontrol(subpan2d,'Style','text',...
       'String','---  = ',...
       'Position', [6 20 80 40],...
       'FontSize',18,...
       'FontName','Helvetica',...
       'ForegroundColor', 'green',...
       'HorizontalAlignment','Left');
    % eigenvalue quality check d3%
    txt12=uicontrol(subpan2d,'Style','text',...
       'String','d3',...
       'Position', [4 01 80 40],...
       'FontSize',18,...
       'FontName','Helvetica',...
       'ForegroundColor', 'green',...
       'HorizontalAlignment','Left');  
    % eigenvalue quality check actual value %
    txt13=uicontrol(subpan2d,'Style','text',...
       'String',num2str(d2/d3, '%3.2g'),...
       'Position', [45 35 40 28],...
       'FontSize',24,...
       'FontName','Helvetica',...
       'ForegroundColor', 'green',...
       'HorizontalAlignment','Center'); 
     
            
       
     
%%%%%%%% Switch Start %%%%%%%%
    button = questdlg('Use this one?', 'Filter Box','Yes','No','Quit','No');
    % disp(['Button equals ',button]);
    switch(button(1))
%       case('<')
%         disp(['i=',num2str(i)])
%         disp(['j=',num2str(j)])
%         disp(['k=',num2str(k)])
%         return;
%         clear all;
      case('N')
        disp('you clicked not to save this one.  load the next')
        return;
        clear all;
      case('Y')
        disp('You have chosen to save this file, but nothing happens yet.')
        fig = gcf;
        anm = num2str(azi);
        pnm = num2str(round(pol));
        dnm = num2str([yr,'_',month,'_',day]);
        thnm = num2str(round(theta));
        phnm = num2str(round(phi));
        tmnm = num2str([ta,'to',tb]);
        filename = [anm,'a',pnm,'p',thnm, 'th', phnm, 'ph', dnm,'_',tmnm, '.png'];
        saveas(fig,filename,'png');
        disp(['File saved as ', filename])
        return;
        clear all;
      case('Q')
        %close all;
        clear all;
        %clc;
    end     
%%%%%%%%% Switch End %%%%%%%%    
    %-----------------------%
    % End GUI Value Display %
    %-----------------------%
    
