function[zs]=dve_angledata_manual(pol,azi,theta0,phi0,zs,V0,j,k)
% Purpose: Formats and prints angle data to the figure for easy reading.
   
    %---------------------------------------%
    % Display Relevant Values on GUI Window %
    %---------------------------------------%    
    pan1 = uipanel('Position', [.01 .33 .98 .30],...
      'BorderWidth',3,...
      'FontSize',12,...
      'ForegroundColor','k',...
      'ShadowColor','k',...
      'BorderType','etchedout',...
      'TitlePosition','lefttop',...
      'FontWeight', 'light');
    %-1st Column Subpanels--------------------------------------------------
    % Polar subpanel %
    subpan1a = uipanel(pan1,'Position', [.01 .50 .20 .48],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','Polar',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');    
    % Azimuth subpanel %
    subpan1b = uipanel(pan1,'Position', [.01 .01 .20 .48],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','Azimuth',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');
    % Azimuth Text %
    txt1=uicontrol(subpan1a,'Style','text',...
       'String',[num2str(azi, '%0.3g'),char(176)],...
       'Position', [4 01 80 40],...
       'FontSize',28,...
       'FontName','Helvetica',...
       'ForegroundColor', 'green',...
       'HorizontalAlignment','Center');
    % Polar Text %
    txt2=uicontrol(subpan1b,'Style','text',...
       'String',[num2str(pol,'%0.3g'),char(176)],...
       'FontSize',28,...
       'FontName','Helvetica',...
       'Position', [4 01 80 40],...
       'ForegroundColor', 'blue',...
       'HorizontalAlignment','Center');
    %---2nd Column Top Subpanel-------------------------------------------------
    % Phi Panel + Title %
    subpan1a = uipanel(pan1,'Position', [.22 .50 .20 .48],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','Phi (GSM)',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');    
    % Theta Panel + Title %
    subpan1b = uipanel(pan1,'Position', [.22 .01 .20 .48],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','Theta (GSM)',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');
    % Phi Text
    txt3=uicontrol(subpan1a,'Style','text',...
       'String',[num2str(phi0, '%1.4g'),char(176)],...
       'FontSize',32,...
       'FontName','Helvetica',...
       'Position', [4 01 100 40],...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Center');
    % Theta Text %
    txt4=uicontrol(subpan1b,'Style','text',...
       'String',[num2str(theta0,'%1.4g'),char(176)],...
       'Position', [4 01 100 40],...
       'FontSize',28,...
       'FontName','Helvetica',...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Center');

%============================BOTTOM BIG PANEL=====================================%

    pan2 = uipanel('Position', [.01 .01 .98 .30],...
      'BorderWidth',3,...
      'FontSize',12,...
      'ForegroundColor','k',...
      'ShadowColor','k',...
      'BorderType','etchedout',...
      'TitlePosition','lefttop',...
      'FontWeight', 'light');
    %------------------1st column bottom subpanel---------------------------
    subpan2a = uipanel(pan2,'Position', [.01 .01 .20 .98],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','V0 (km/s in GSM)',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');
    % V0 (xGSM) Text
    txt5=uicontrol(subpan2a,'Style','text',...
       'String',['x= ',num2str(V0(1), '%1.3g')],...
       'FontSize',20,...
       'FontName','Helvetica',...
       'Position', [4 60 100 40],...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Left');
    % V0 (yGSM) Text %
    txt6=uicontrol(subpan2a,'Style','text',...
       'String',['y= ',num2str(V0(2),'%1.3g')],...
       'Position', [4 30 100 40],...
       'FontSize',20,...
       'FontName','Helvetica',...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Left');
    % V0 (zGSM) Text
    txt7=uicontrol(subpan2a,'Style','text',...
       'String',['z= ',num2str(V0(3), '%1.3g')],...
       'FontSize',20,...
       'FontName','Helvetica',...
       'Position', [4 01 100 40],...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Left');
    %------------------2nd column bottom subpanel---------------------------
    subpan2b = uipanel(pan2,'Position', [.22 .01 .20 .98],...
      'BorderWidth',2,...
      'FontSize',10,...
      'ShadowColor','k',...
      'HighlightColor','k',...
      'ForegroundColor','k',...
      'Title','ZS (unit)',...
      'BorderType','line',...
      'TitlePosition','centertop',...
      'FontWeight', 'light');
    % zs (xGSM) Text
    txt8=uicontrol(subpan2b,'Style','text',...
       'String',['x= ',num2str(zs(1), '%0.3g')],...
       'FontSize',20,...
       'FontName','Helvetica',...
       'Position', [4 60 100 40],...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Left');
    % zs (yGSM) Text %
    txt9=uicontrol(subpan2b,'Style','text',...
       'String',['y= ',num2str(zs(2),'%0.3g')],...
       'Position', [4 30 100 40],...
       'FontSize',20,...
       'FontName','Helvetica',...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Left');
    % zs (zGSM) Text
    txt10=uicontrol(subpan2b,'Style','text',...
       'String',['z= ',num2str(zs(3), '%0.3g')],...
       'FontSize',20,...
       'FontName','Helvetica',...
       'Position', [4 01 100 40],...
       'ForegroundColor', 'k',...
       'HorizontalAlignment','Left');

     
   
